sudo: true
osx_image: xcode7.3
language: objective-c
rvm: 2.2.4

before_script: bundle install

script:
  - bundle exec rake
  - bundle exec sudo rspec --tag sudo
  - bundle exec rspec --tag ~sudo
  - bundle exec rubocop
